### ISSUE TITLE
Gaming Dashboard Analytics

### ISSUE THREAD

**Issue by serenaho** [ChainSafe/game-web3gl#39]
**To-Do Checklist for Gaming Dashboard Analytics:**

- [ ] Research General Analytics, On-Chain Analytics, other precedents
- [ ] Research data visualization
- [ ] Create a user interview script to approach users
- [ ] Talk to users to get feedback on need and wants
- [ ] Develop personas
- [ ] First designed iteration of Analytics
- [ ] User Feedback round 1
- [ ] Further design development based on feedback
- [ ] User Feedback round 2
- [ ] Shipping & Implementation

Assigned to: @serenaho
